version: '3'
networks:
  green-eats:

services:
  # app:
  #   build: .
  #   networks:
  #     - green-eats
  #   hostname: green-eats.app
  #   container_name: ge_app
  #   platform: linux/x86_64
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
    
  db:
    image: postgres:10.3
    restart: always
    networks:
      - green-eats
    hostname: green-eats.db
    container_name: ge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    networks:
      - green-eats
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres: